### ISSUE TITLE
Keyboard commands break zapping/commenting

### ISSUE THREAD

**Issue by blastshielddown** [wavlake/wavman#40]
Pressing `Enter` when trying to submit a zap amount or comment breaks the player. Possibly due to keyboard controls not being mapped properly for those forms.

**Comment by joshr4** [comment]
turns out this is an outstanding bug, unrelated to the recent keyboard PR. By default, forms are submitted whenever enter is pressed, so we need to stop that default behavior.

https://stackoverflow.com/questions/43750335/react-prevent-form-submission-when-enter-is-pressed-inside-input
https://github.com/wavlake/wavman/pull/41

**Comment by blastshielddown** [comment]
Resolved by #41
